<?php

/**
 * Implements hook_menu()
 */
function student_form_menu()
{
    $items['student_list/add_student'] = array(
        'title' => 'Add student form',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('student_form_add_one'),
        'type' => MENU_LOCAL_TASK,
        'access callback' => TRUE,
        'weight' => 1,
    );

    return $items;
}

// Form to add students
function student_form_add_one($form, &$form_state) {
    $form['document_id'] = array(
        '#type' => 'textfield',
        '#title' => "Document id",
        '#required' => 'True',
    );
    $form['pib'] = array(
        '#type' => 'textfield',
        '#title' => "Pib",
        '#required' => 'True',
    );
    $form['description'] = array(
        '#type' => 'textarea',
        '#title' => "Description",
    );
    $form['birthday_year'] = array(
        '#type' => 'textfield',
        '#title' => "Birthday year",
    );
    $form['gender'] = array(
        '#type' => 'radios',
        '#title' => "Gender",
        '#options' => array('M' => t('Male'), 'F' => t('Female')),
        '#required' => 'True',
    );
    $form['student_group'] = array(
        '#type' => 'textfield',
        '#title' => "Student group",
    );
    $form['average_score'] = array(
        '#type' => 'textfield',
        '#title' => "Average score",
    );
    $form['photo_fid'] = array(
        '#type' => 'managed_file',
        '#title' => "Photo",
        '#description' => t('Allowed extensions: gif png jpg jpeg'),
        '#upload_location' => 'public://',
        '#required' => 'True',
        '#upload_validators' => array(
            'file_validate_extensions' => array('gif png jpg jpeg'),
            'file_validate_size' => array(100*1024),
        ),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    $form['#attached']['js'][] = drupal_get_path(
            'module', 'student_form') . '/js/student_form_validate.js';

    return $form;
}


// submit form handler
function student_form_add_one_submit($form, &$form_state)
{
    // Load the file
    $file = file_load($form_state['values']['photo_fid']);
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);

    db_insert('student_list_data')
        ->fields(array(
            'document_id' => $form_state['values']['document_id'],
            'pib' => $form_state['values']['pib'],
            'description' => $form_state['values']['description'],
            'birthday_year' => $form_state['values']['birthday_year'],
            'gender' => $form_state['values']['gender'],
            'student_group' => $form_state['values']['student_group'],
            'average_score' => $form_state['values']['average_score'],
            'photo_fid' => $form_state['values']['photo_fid'],
        ))
        ->execute();

    //dpm($form_state);

    drupal_goto('student_list');
}


// submit form validate (server-side)
function student_form_add_one_validate($form, &$form_state) {
    if (!is_numeric($form_state['values']['document_id'])) {
        form_set_error('document_id', 'Document id must be NUMBER!');
    }

    if (is_float(++$form_state['values']['document_id'])) {
        form_set_error('document_id', 'Document id must be INTEGER number!');
    }

    if (!is_numeric($form_state['values']['birthday_year']) || $form_state['values']['birthday_year'] < 1901 || $form_state['values']['birthday_year'] > 2155) {
        form_set_error('birthday_year', 'Birthday year must be number in the RANGE 1901 to 2155!');
    }

    if (is_float(++$form_state['values']['birthday_year'])) {
        form_set_error('document_id', 'Birthday year must be INTEGER number!');
    }

    if (!is_numeric($form_state['values']['average_score'])) {
        form_set_error('average_score', 'Average score must be NUMBER!');
    }

}

/*
function student_form_add_js_settings($settings) {
    // add js script
    drupal_add_js(drupal_get_path('module', 'student_form') . '/jquery-validate/jquery.validate.js');
    drupal_add_js(drupal_get_path('module', 'student_form') . '/jquery-validate/jquery.validate.min.js');

}
*/